apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "django_db"